version: '3'
services:
    app:
        build:
            context: ./resources/docker
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - inetrnal
        depends_on:
            - mysql
        ports:
        - 8080:80

    mysql:
      image: 'mysql:8.0'
      ports:
        - '3306:3306'
      environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      volumes:
        - 'sailmysql:/var/lib/mysql'
      networks:
        - inetrnal
      healthcheck:
        test: ["CMD", "mysqladmin", "ping"]
      container_name: mysql

networks:
    inetrnal:
        driver: bridge
volumes:
    sailmysql:
        driver: local
